name: cse_class_managment
description: "A Flutter project for CSE Student in NUBTK"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #  Firebase .....
  firebase_core: ^3.3.0
  #  cloud firestore
  cloud_firestore: ^5.2.1
  #  For svg Image
  flutter_svg: ^2.0.10+1
  #  For Toast Message
  #  fluttertoast: ^8.2.8
  #  For Date and Time
  intl: ^0.19.0
  #  For Lotti Animation
  lottie: ^3.1.2
  # For local Storage
  shared_preferences: ^2.0.8
  #  Firebase Storage
  firebase_storage: ^12.1.3
  #  For Phone Call
  android_intent_plus: ^5.2.0
  #  For Image Pick
  image_picker: ^1.1.2
  #  url_launcher:
  url_launcher: ^6.3.0
  #  HTTP
  http: ^1.2.2
  sqflite: ^2.0.0+4
  path: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg_image/
    - assets/lotti_animation/
  fonts:
    - family: kalpurush
      fonts:
        - asset: fonts/kalpurush.ttf
        - asset: fonts/Poppins-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
